apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: craftista-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/akhileshmishrabiz/k8s-bootcamp-dec25.git
    targetRevision: main
    path: class11-12/k8s-menifests/argocd-apps
    directory:
      recurse: true
      exclude: 'apps/*'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
