apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: node:18-alpine
        command: ["npx", "serve", "-s", "build", "-l", "3000"]
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: app
spec:
  selector:
    app: react
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP



### new dep test 

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:latest
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-app-svc
# spec:
#   selector:
#     app: nginx
#   ports:
#   - port: 80
#     targetPort: 80
#   type: ClusterIP
