apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devopsdojo
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64 
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nslookup devopsdojo-db-service.devopsdojo.svc.cluster.local; do echo waiting for database; sleep 2; done;']
        # database -> service_name.namespace.svc.cluster.local
        # also databae service -> hostname.port.cluster.local
      containers:
      - name: backend
        image: 307946636515.dkr.ecr.us-east-1.amazonaws.com/devopsdojo-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # - name: ALLOWED_ORIGINS
        #   # value: "https://devopsdojo.rajeshapps.site,http://devopsdojo.rajeshapps.site,https://app.rajeshapps.site,http://app.rajeshapps.site"
        #   value: "*"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: SECRET_KEY
        - name: FLASK_DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_DEBUG
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devopsdojo
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP