apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devopsdojo
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 307946636515.dkr.ecr.us-east-1.amazonaws.com/devopsdojo-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        # - name: NAMESPACE
        #   value: devopsdojo

        - name: BACKEND_URL
          # value: "http://backend.devopsdojo.svc.cluster.local:8000"
          # value: "/api"
          # value: "https://devopsdojo.rajeshapps.site"
          value: "https://devopsdojo.rajeshapps.site"


      # this way frontend builds a backend link
      # backend.namespace.svc.cluster.local
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: devopsdojo
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
