# name: "Dev build and push"

# on:
#   # push:
#   #   branches:
#   #     - main
#   #   paths:
#   #     - app/**
#   workflow_dispatch:

# env:
#   environment: "dev"
#   region: "us-east-1"
#   deployment_info: "app-deploy-data"

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Configure AWS Credentials
#         if: ${{ github.ref == 'refs/heads/main' }}
#         uses: aws-actions/configure-aws-credentials@v3
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.region }}

#       - name: Fetch secrets from AWS Secrets Manager
#         id: fetch-secrets
#         uses: aws-actions/aws-secretsmanager-get-secrets@v2
#         with:
#           secret-ids: |
#             ,${{ env.environment }}-${{ env.deployment_info }}
#           parse-json-secrets: true

#       - name: Build docker container
#         uses: docker/build-push-action@v6
#         with:
#           context: "{{defaultContext}}:app"
#           tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
#           build-args: APP_VERSION=${{ github.sha }}
#           push: false

#       - name: Login to Amazon ECR
#         if: ${{ github.ref == 'refs/heads/main' }}
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2
#         with:
#           mask-password: true
#           registries: ${{ env.ACCOUNT_ID }}

#       - name: Push image to Amazon ECR
#         if: ${{ github.ref == 'refs/heads/main' }}
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
#           IMAGE_NAME: ${{ env.IMAGE_NAME }}
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
#           docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

#       - name: Trigger Deploy Workflow in Another Repository
#         run: |
#           # Set the required variables
#           repo_owner="rajeshchandranaws3" 
#           repo_name="web-app-on-aws-ecs"  
#           event_type="trigger-workflow" 
#           image_tag="${{ github.sha }}"
#           environment="${{ env.environment }}"
#           deployment_info="${{ env.deployment_info }}"
  
#           curl -L \
#             -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.PAT }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
#             -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"deployment_info\": \"$deployment_info\", \"environment\": \"$environment\", \"image_tag\": \"$image_tag\", \"unit\": false, \"integration\": true}}"
#         shell: bash